import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";

export const metadata: Metadata = {
  title: "Sebastian Dev",
  description: "Generated by vercel with a lot of love",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <Navbar />
        <div className={"flex flex-col justify-center items-center h-screen "}>
          {children}
        </div>
      </body>
    </html>
  );
}
